### ISSUE TITLE
Internal Service Error

### ISSUE THREAD

**Issue by SteffeyDev** [electrode-io/electrode-ota-server#10]
When I click on Github button on the main page of the Hapi server, I get a blank page with the text "An internal server error occurred" on it.  I can't find any logs and the url is being redirected to "https://example.com/auth/login/github?hostname=".  My relevant config section looks like this:
`"electrode-ota-server-auth": {
            "options": {
                "strategy": {
                    "github-oauth": {
                        "options": {
			    "isSecure": true,
                            "clientId": "xxxxxx",
                            "clientSecret": "xxxxxxx"
                        }
                   },
                   "session": {
                        "options": {
                            "isSecure":true
                        }
                   }
               }
            }
        }`

Any ideas how to get this working? I feel like I am missing something.  Thanks in advance for any help.

**Comment by taina0407** [comment]
@SteffeyDev 
I think you've doing it wrong way.
You should run command `code-push register https://<%=your_ota_server%>` in your terminal, then it will open webbrowser to the ota server, then you can click on github button to login and follow authenticate steps.

Please follow the instruction here http://www.electrode.io/docs/electrode_react_native_over_the_air_electron.html

**Comment by datvong-wm** [comment]
Please check your settings under /config.  Search for example.com and replace with github.com, or remove the setting.
