### ISSUE TITLE
[Error]  Payload content length greater than maximum allowed: 1048576

### ISSUE THREAD

**Issue by afces1** [electrode-io/electrode-ota-server#12]
**Description**

Included in React Native iOS bundle is a set of images imported to \<Image\> components via require() syntax.   However, when size of image assets exceed 1MB, code-push is unable to build a release bundle due to reported error:

[Error]  Payload content length greater than maximum allowed: 1048576

Can you provide specific instructions on how to increase Hapi payload maxBytes configuration in order to resolve this error?

**Reproduction Steps and Sample Code**

Setup electrode-ota-server and cassandra running locally
Register and login code-push tools referencing electrode-ota-server
Create a React Native project
Add images inside an assets folder under project and require the images inside index.ios.js.
Make sure images total more than 1MB
Invoke code-push release-react to generate a code-push main bundle.
   - content length failure occurs at step: "Releasing update contents to CodePush."

**Additional Information**

Electrode OTA Server version: 2.0.0-beta.1
Code-push CLI version: 1.12.9-beta
React Native version: 0.42.3
Platform: iOS
Development Operating System: macOS Sierra

**Comment by awhelms** [comment]
I ran into this as well.  Got around it by adding this to my configuration under plugins:

```JavaScript
        "electrode-ota-server-routes-apps" : {
            options : {
                payload : {
                    maxBytes : 94371840
                }                
            }
        },
```

Electrode OTA is written as an Electrode server which in turn uses Hapi.  Hapi imposes a 1MB limit.  Electrode OTA exposes the above configuration option to get around it.

**Comment by afces1** [comment]
@awhelms thank you so much for this hint!!  I'm able to release code-push with asset payload higher than 1MB.  hopefully electrode-ota-server project will document this configuration change or include as an example config.
