### ISSUE TITLE
Is it possible to config othter oauth2 provider?

### ISSUE THREAD

**Issue by dxpengyi1990** [electrode-io/electrode-ota-server#14]
I dont't want to use github ,because I have my own oauth2 server. Does current server support that function?

**Comment by awhelms** [comment]
From what I can gather, it uses the bell plugin for hapijs to swap out oauth providers.  https://github.com/hapijs/bell.   I am not sure what you need to put in your config to make it work for your server though.  You may also need to write your own plugin similar to the electrode-ota-server-auth-github (https://github.com/electrode-io/electrode-ota-server/tree/master/electrode-ota-server-auth-github).

**Comment by jspears** [comment]
You can,  I had it working against github and azure a while back out of the box. Its been a while so I don't remember all the magic.   You shouldn't have to do the auth-github thing, as that is a fix to github's oatuth, that doesn't return email like it should.

**Comment by datvong-wm** [comment]
As awhelms and jspears has mentioned, you can use https://github.com/hapijs/bell for your auth layer.
