### ISSUE TITLE
documentation link is broken

### ISSUE THREAD

**Issue by trampi** [electrode-io/electrode-ota-server#167]
Hello there,

as our team is trying to implement updates via code push, I am investigating into electrode-ota-server.
However, the link to the documentation is at the moment unavailable.
See https://docs.electrode.io/other/powerful-electrode-tools/react-native-and-over-the-air

It would be awesome if you could look into that, as electrode-ota-server sounds very promising.

All the best,
trampi

**Comment by datvong-wm** [comment]
Thank you for bringing this to our attention.  We are in the process to moving documentation around, so this will be resolved soon.

**Comment by datvong-wm** [comment]
For now, please reference https://github.com/electrode-io/electrode-io.github.io/blob/master/_docs/05.1-electrode_react_native_over_the_air_electron.markdown

**Comment by trampi** [comment]
Thanks @datvong-wm for the quick update, I will use the provided link.
