### ISSUE TITLE
`Error adding access key` when attempting to use example ota server file

### ISSUE THREAD

**Issue by patrickhurtado** [electrode-io/electrode-ota-server#168]
Hey all!

I'm trying to run the example given in `electrode-ota-server/example`, but am hitting an error when attempting to sign in via github. On the galaxy page, I see a `Error adding access key` error. I provided a password, a client secret, and client key. Am I missing anything else that I need to give it in `config/development.json` to get it to work?

Thanks in advanced!

**Comment by datvong-wm** [comment]
Check the logs.  Make sure you register first before you signin.  `code-push register`
