### ISSUE TITLE
Error: Cannot find module node_modules/.bin/electrode-ota-server

### ISSUE THREAD

**Issue by sdg9** [electrode-io/electrode-ota-server#17]
Heads up the docs at http://www.electrode.io/docs/electrode_react_native_over_the_air_electron.html

> In package.json add By default the server will start with production config. This can be overridden with NODE_ENV.
> 
> ```js
> "scripts":{
>   "start":"NODE_ENV=production node node_modules/.bin/electrode-ota-server",
>   "development":"NODE_ENV=development node node_modules/.bin/electrode-ota-server"
> 
> }
> ```

Don't align with the examples (which are correct) in this repo since the v2 changes.

```js
  "scripts": {
    "start": "NODE_ENV=development node $NODE_DEBUG_OPTION ./node_modules/electrode-ota-server/index"
  },
```

**Comment by datvong-wm** [comment]
Both lines will work.  `node_modules/.bin/electrode-ota-server` links to `node_modules/electrode-ota-server/index`
