### ISSUE TITLE
Cannot register or login user while using GitLab provider from bell.js

### ISSUE THREAD

**Issue by ikhilko** [electrode-io/electrode-ota-server#35]
I'm trying to setup Electrode OTA to use gitlab auth, and facing issue when after successfully auth on GitLab side  user permanently redirected to /auth/login insead of /accesstoken route. After a day of debugging I'm found that the same issue is reproducible for GitHub auth (only first time, when grant access for app on GitHub page).
So the issue is related to [hapi-auth-cookie](https://github.com/hapijs/hapi-auth-cookie) using "SameSite=Strict" attribute for cookie that is a root of problem.
Could you please update version of [hapi-auth-cookie](https://github.com/hapijs/hapi-auth-cookie) > 7.0.0 to make it possible to configure SameSite behavior?

A full description of problem you can read [here](https://medium.com/@PeterNagyJob/how-did-i-waste-6-hours-finding-out-all-about-same-site-cookies-82d75062ede2)

**Comment by datvong-wm** [comment]
hapi-auth-cookie used in release v3.2.6-0.  can you please verify if that solves your issue?

thanks!

**Comment by ikhilko** [comment]
@datvong-wm as I can see currently new version is not published to npm, do I need to check before you will publish it?

**Comment by datvong-wm** [comment]
Sorry about that.  Thought I did publish it, but turned out I didn't.  Just published right now.

**Comment by ikhilko** [comment]
@datvong-wm Hi again, looks like issue resolved, thanks! :)
