### ISSUE TITLE
Bundle upload error over 1MB.

### ISSUE THREAD

**Issue by sdg9** [electrode-io/electrode-ota-server#4]
When running `code-push release-react MyTestApp android --deploymentName Staging` I get the following error as the bundle is being uploaded to the server

```
Releasing update contents to CodePush:

Upload progress:[==================================================] 100% 0.0s
[Error]  Payload content length greater than maximum allowed: 1048576
```

**Comment by sdg9** [comment]
After doing some research I found hapi defaults upload size to 1MB which can be [overwritten by setting maxBytes](https://hapijs.com/api). 

I resolved this issue for me by cloning the project and adding a larger maxBytes size such as
```javascript
payload: {
  maxBytes: 4082153,
},
```
to the config object in [apps.js](https://github.com/electrode-io/electrode-ota-server/blob/master/server/routes/apps.js#L76)

**Comment by jspears** [comment]
Thanks for the note.   I'll update something to make this easer to find.
