### ISSUE TITLE
Request Timeout on realease

### ISSUE THREAD

**Issue by muratkarakas** [electrode-io/electrode-ota-server#63]
Hi,

On my local machine I have no release problem. With the same setup(I use docker)  possibly because of network delay it takes longer time  to upload package to server and after while gives the following error. Is this timeout comes from client or server? I couldn't find anything on the code-push client side about timeout. (I've no network access problem, I can register/login successfully and I can see the token validation/deployment request logs when I run release)

Releasing update contents to CodePush:

Upload progress:[==================================================] 100% 0.0s
[Error]  Request Timeout**

Thanks

**Comment by awhelms** [comment]
I ran into this too.  You can increase the timeout using the same setting that you used for increasing the payload size.  It's a Hapi setting.

```JavaScript
        "electrode-ota-server-routes-apps": {
            options: {
                payload: {
                    // ~90MB
                    maxBytes: 94371840,
                    timeout: 119999,   // <====================
                }
            }
        },
```

**Comment by muratkarakas** [comment]
Thanks
