### ISSUE TITLE
No history of package for IOS

### ISSUE THREAD

**Issue by muratkarakas** [electrode-io/electrode-ota-server#66]
Hi,
We are using code-push  with react-native(IOS + Android). When we build release apk at the same time we release  codepush deployment

> code-push release-react MyMobileAndroidApp android => Android

> code-push release-react MyMobileIOSApp ios  => IOS

then after installing apk there isn't any problem  with update lifecycle(If there is is a new package It prompts for installation based on our configuration). 
For IOS after sending package to test flight(At the same time we release to code-push also) it never prompts for new package
 .When I check the ota-server logs ; it says 

> No history of package: 1a90c52351bd302c9433890d3894a52eXXXXXX.

 What is the possible reason for this or is it possible to  by pass package hash history check ?

Thanks

**Comment by datvong-wm** [comment]
An extra hash check is causing issues in some cases.  The latest version v4.4.7 has this check removed.
