### ISSUE TITLE
What is the exact link on which the bundle is server from?

### ISSUE THREAD

**Issue by kaushikwavhal** [electrode-io/electrode-ota-server#79]
i've followed this document and installed electrode-server 
https://github.com/electrode-io/electrode/blob/master/docs/chapter1/over-the-air/react-native-and-over-the-air.md.

Also my config json file has **downloadUrl** set to "http://localhost:8081/storagev2/" in the electrode-ota-server-fileservice-upload block.

But when the server starts, i get a 404 at http://10.14.21.123:9001/storagev2/

even though I am able to do the auth and get the key at the same place http://10.14.21.123:9001

**Comment by datvong-wm** [comment]
downloadUrl should be set to "http://10.14.21.123:9001/storagev2/".  This is where you are running your server and where the mobile app will hit to check for new updates and download packages.

**Comment by kaushikwavhal** [comment]
I've changed the downloadUrl parameter and now it is set to `http://10.14.21.123:9001/storagev2/` but i still get a 404.

**Comment by datvong-wm** [comment]
The path is defined here
https://github.com/electrode-io/electrode-ota-server/blob/d24957dbda7bd260a58283bfc7592b9a1ac42605/electrode-ota-server-routes-acquisition/src/index.js#L45

Note you need the hash to return something meaningful.

**Comment by kaushikwavhal** [comment]
Okay yes. I can download the binary when i append the hash to the url. Thanks.
