### ISSUE TITLE
is it possible to deploy server by Pm2 ?

### ISSUE THREAD

**Issue by vanhungoz** [electrode-io/electrode-ota-server#84]
hi dev team, thanks for your great work. i set up my project like example then use pm2 start index.js to deploy my server. but it always returns require(...) is not function

**Comment by datvong-wm** [comment]
What node version are you on?  Can you include the entire logs?

**Comment by vanhungoz** [comment]
<img width="540" alt="screen shot 2019-01-26 at 9 02 56 am" src="https://user-images.githubusercontent.com/35133417/51781281-33638480-2149-11e9-9499-4659ee991181.png">
my version is 10.15.0

**Comment by vanhungoz** [comment]
<img width="575" alt="screen shot 2019-01-26 at 9 04 39 am" src="https://user-images.githubusercontent.com/35133417/51781297-7f162e00-2149-11e9-9b49-00c1b7bd0ff3.png">
this is logs

**Comment by vanhungoz** [comment]
<img width="279" alt="screen shot 2019-01-26 at 9 06 27 am" src="https://user-images.githubusercontent.com/35133417/51781309-aff66300-2149-11e9-86cf-51899262c259.png">
this is my index,js file

**Comment by vanhungoz** [comment]
<img width="368" alt="screen shot 2019-01-26 at 9 07 41 am" src="https://user-images.githubusercontent.com/35133417/51781329-dae0b700-2149-11e9-994e-1e6fbfe6d7fb.png">
i also try

**Comment by datvong-wm** [comment]
For PM2, use `node_modules/electrode-ota-server/index.js`

**Comment by vanhungoz** [comment]
i also try it, but it didn't work

**Comment by vanhungoz** [comment]
with same error

**Comment by vanhungoz** [comment]
i can deploy it , thank you very much

**Comment by vanhungoz** [comment]
hi, @datvong-wm , i use pm2 start index.js (node_modules/electrode-ota-server/index.js) to deploy it, sometimes, it show error "clientId is required"

<img width="566" alt="Screen Shot 2019-03-11 at 9 52 13 AM" src="https://user-images.githubusercontent.com/35133417/54097577-65703380-43e3-11e9-8cc1-38cd5a773ec6.png">

**Comment by vanhungoz** [comment]
i have no ideal for that

**Comment by vanhungoz** [comment]
i resolved my bug :)
