### ISSUE TITLE
App can't update

### ISSUE THREAD

**Issue by vanhungoz** [electrode-io/electrode-ota-server#85]
i use code-push to publish a new version of my app. this new version is displayed in electrode OTA Desktop, but when i press update button in my app to check manualy new version in server. it always returns undefined

**Comment by vanhungoz** [comment]
<img width="1273" alt="screen shot 2019-01-25 at 3 19 56 pm" src="https://user-images.githubusercontent.com/35133417/51734652-c0f69400-20b7-11e9-897f-52343ed49d1d.png">

**Comment by vanhungoz** [comment]
<img width="1280" alt="screen shot 2019-01-25 at 3 33 59 pm" src="https://user-images.githubusercontent.com/35133417/51734679-d4096400-20b7-11e9-90a4-d25871cd31ed.png">
my app is installing version 1.0.6, i saw api checkUpdate alway return undefined

**Comment by vanhungoz** [comment]
i check a lot of times, it is not working. i set up by tutorial in electrode home page.

**Comment by vanhungoz** [comment]
<img width="553" alt="screen shot 2019-01-25 at 3 50 42 pm" src="https://user-images.githubusercontent.com/35133417/51735108-0d8e9f00-20b9-11e9-81ae-1578bb3a7538.png">
this is my server config

**Comment by datvong-wm** [comment]
From the log, it looks like there is a update ("available": true).  The undefined just means there's no message to that particular log.  Check to make sure you actually have a change to your package.  The server calculates a difference between the versions and only returns the diff if any.
Check the deployment_package_history table.

**Comment by vanhungoz** [comment]
thank you for your reply. i am sure there are many changes in my Package

**Comment by vanhungoz** [comment]
i have tested with Microsoft code push server and it has worked. 
then i change to use electrode ota server. i really don't know why it doesn't work. i try it many times

**Comment by datvong-wm** [comment]
It might be the packageHash is different.   You'll have to debug it manually.  In electrode-ota-server-model-acquisition, there is a /lib/acquisition.js:66 . that is the piece of code that determines what to return.

**Comment by vanhungoz** [comment]
yes, i'll check it.

**Comment by vanhungoz** [comment]
hi @datvong-wm . i use "describe tables" to get all table of keyspaces, the "ota_db2" keyspace don't have any table
<img width="330" alt="screen shot 2019-01-26 at 9 40 24 am" src="https://user-images.githubusercontent.com/35133417/51781674-9a376c80-214e-11e9-9b10-381c40b129a8.png">

**Comment by vanhungoz** [comment]
i have resolved it. thanks for your great support :)
