### ISSUE TITLE
Update Status Problem

### ISSUE THREAD

**Issue by muratkarakas** [electrode-io/electrode-ota-server#9]
Hi,
After successfull update sync process(with code-push cordova) update status is always "available" so it tries to download whenever sync process is called on the client side. After debugging electrode-ota-server I found that in "acquisition.js" file "isNotAvailable" varilable is  passed into makeReturn parameter with wrong name; makeReturn accepts this variable as "isAvailable". After changing "isNotAvailable" to " !isNotAvailable  " as shown below it worked correctly. Can you check it please?

return isNotAvailable ? **makeReturn(!isNotAvailable)** : api.isUpdateAble(params.clientUniqueId, pkg.packageHash, pkg.rollout).then(makeReturn);

Thanks

**Comment by awhelms** [comment]
I ran into this also.  I made the change you suggested in my local copy, but now the client always thinks it's up-to-date, even when there are updates available.  Were you able to get around that?

**Comment by awhelms** [comment]
With regard to my previous comment, I discovered that the zip I was uploaded was always the same content (I'm using an ionic project, but wasn't performing some of ionic's build scripts).  The server was letting me upload anyway but the content hash wasn't changing, so the client thought it already had the update.  Microsoft's server will warn if you are uploading the same content for an update, so I guess we need to figure out a way to make this one do the same (in addition to the fix you mentioned above, @muratkarakas).

**Comment by awhelms** [comment]
The fix from above has been merged.
